version: "3.9"
services:
  equipment-service:
    build: ./equipment-service
    image: micro/equipment-service:dev
    container_name: equipment-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
  trainer-service:
    build: ./trainer-service
    image: micro/trainer-service:dev
    container_name: trainer-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
  member-service:
    build: ./member-service
    image: micro/member-service:dev
    container_name: member-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
  class-service:
    build: ./class-service
    image: micro/class-service:dev
    container_name: class-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - trainer.service.url=http://trainer-service:8080
      - equipment.service.url=http://equipment-service:8082
      - member.service.url=http://member-service:8081

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - class-service
      - equipment-service
      - member-service
      - trainer-service
